/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.mokkapps.gamenews.api;

import de.mokkapps.gamenews.api.model.Article;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-02-23T13:05:35.987+01:00[Europe/Berlin]")

@Api(value = "News", description = "the News API")
public interface NewsApi {

    /**
     * GET /news : Get list of latest gaming news
     *
     * @return Expected response to a valid request (status code 200)
     */
    @ApiOperation(value = "Get list of latest gaming news", nickname = "getNews", notes = "", response = Article.class, responseContainer = "List", tags={ "News", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Expected response to a valid request", response = Article.class, responseContainer = "List") })
    @RequestMapping(value = "/news",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<Article>> getNews();

}
